### ISSUE TITLE
Lua script for Gales look disordered

### ISSUE THREAD

**Issue by Jellal93** [DevonStudios/LuaScripts#6]
Mayor thanks to @KapitalRoser for fixing the IV issue on party! Can confirm that Hidden Power is now displayed properly :)

It seems that the view is now a bit disordered and looks out of place. Just pulling this as @Real96 requested it. This is how it looks now. Was there supposed to be an alignment? 
![image](https://user-images.githubusercontent.com/37722198/144352660-88a035b0-3ffd-49e3-86b1-8e339a6d26eb.png)

**Comment by KapitalRoser** [comment]
Your screenshots from the other issue had this too. 
Figured it out! Using Direct 3D 11 as your graphics backend throws off the alignment. 
For comparison, this is how it is supposed to look when using OpenGL:

![image](https://user-images.githubusercontent.com/72572527/144354295-cb4f06fd-5520-4498-a98f-0354ad777322.png)
