### ISSUE TITLE
Script doesn't shows the PID hit for roamer Thundurus on Pokemon Black

### ISSUE THREAD

**Issue by Jellal93** [DevonStudios/LuaScripts#7]
![image](https://user-images.githubusercontent.com/37722198/145934270-e7f5c474-96e5-4db8-9b1c-6ed841d293e2.png)

The Gen 5 BW lua script displays the correct PID hit on Pokemon White and it works as intended since it shows the PID I hit for Tornadus. However, it doesn't displays the PID you hit in Pokemon Black:

![image](https://user-images.githubusercontent.com/37722198/145934371-ea1b7e54-8824-4c74-9448-f0ade3359087.png)
After hitting the PID, the script doesn't shows it on Pokemon Black and I am not able to see what Thundurus I hit.

I believe this might be an issue since it is not showing the right RAM address to verify the PID. Both roamers have different addresses on each games. Thundurus RAM address is on 0223D6D8

![image](https://user-images.githubusercontent.com/37722198/145934551-92ae4105-7dd4-4300-865c-7cc6918b7deb.png)

**Comment by Jellal93** [comment]
Ooops I forgot to add this: 
![image](https://user-images.githubusercontent.com/37722198/145934874-ce249339-164a-42a0-9d7f-8323bbaecf5e.png)

**Comment by Real96** [comment]
Fixed
